### ISSUE TITLE
diagbox 在 array 中不能直接使用

### ISSUE THREAD

**Issue by lvjr** [leo-liu/tex-pkg#33]
目前 \diagbox 命令只能在 tabular 里使用，无法在 array 中直接使用。虽然有办法可以解决，但若宏包能直接支持会更方便。

在 array 中使用的一个典型场景是排版概率论的二维随机变量的概率分布表。在 array 中使用 \diagbox 命令时，若能自动把两个（或三个）参数放入 $...$ 里，那就更好了。

**Comment by leo-liu** [comment]
可以理解。不过现在很少维护了，看了一下改动地方还不少，有空再说吧。

**Comment by lvjr** [comment]
正如上面提到的 issue，在我的 `tabularray` 宏包里已经对数学环境作特别处理，这个需求已经得到满足。
